replicaCount: 1
strategyType: Recreate

image:
  repository: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner
  tag: v4.0.2
  pullPolicy: IfNotPresent

nfs:
  server: nfs-tools-project.svc.eqiad.wmnet
  # This is set to toolsbeta's path for now.
  path: /srv/misc/shared/toolsbeta/project/pvs
  mountOptions:
    - noatime
    - nfsvers=4
    - proto=tcp
    - sec=sys
  volumeName: nfs-subdir-external-provisioner-root

storageClass:
  defaultClass: true
  archiveOnDelete: false

podSecurityPolicy:
  enabled: true

resources:
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 128Mi

labels:
  app.kubernetes.io/part-of: toolforge-build-service

# deployed via: helm --kube-as-user bstorm --kube-as-group system:masters --namespace nfs-provisioner install nfs-provisioner-beta-1 nfs-subdir-external-provisioner/nfs-subdir-external-provisioner -f volume-provisioner-values.yaml
