apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test4-pvc
  namespace: image-build
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
