apiVersion: v1
kind: PersistentVolume
metadata:
  name: minikube-user-pvc
  namespace: image-build
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/minikube-user-pvc/
